#pragma once

#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <string>
#include <math.h>

/**
* GripPipeline class.
* 
* An OpenCV pipeline generated by GRIP.
*/
class GripPipeline {
	public:
		GripPipeline() = default;
		void Process(cv::Mat& source0);
		cv::Mat* GetHsvThresholdOutput();
		std::vector<std::vector<cv::Point> >* GetPolyDPOutput();
		std::vector<std::vector<cv::Point> >* GetFindContoursOutput();
		std::vector<std::vector<cv::Point> >* GetFilterContoursOutput();
		std::vector<std::vector<cv::Point> >* GetConvexHullsOutput();

	private:
		cv::Mat hsvThresholdOutput;
		std::vector<std::vector<cv::Point> > polyDPOutput;
		std::vector<std::vector<cv::Point> > findContoursOutput;
		std::vector<std::vector<cv::Point> > filterContoursOutput;
		std::vector<std::vector<cv::Point> > convexHullsOutput;
		void hsvThreshold(cv::Mat &, double [], double [], double [], cv::Mat &);
		void polyDP(std::vector<std::vector<cv::Point> > &, double epsilon, bool closed, std::vector<std::vector<cv::Point> > &out);
		void findContours(cv::Mat &, bool , std::vector<std::vector<cv::Point> > &);
		void filterContours(std::vector<std::vector<cv::Point> > &, double , double , double , double , double , double , double [], double , double , double , double , std::vector<std::vector<cv::Point> > &);
		void convexHulls(std::vector<std::vector<cv::Point> > &, std::vector<std::vector<cv::Point> > &);
};
// end namespace grip


